kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
  namespace: ricardo
spec:
  replicas: 3
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: data-stone:ricardo
          command: ["/spark-worker"]
          ports:
            - containerPort: 7337 #randon port Schedule executors
          resources:
            requests:
              memory: "900m"
              cpu: "900m"
            limits:
              memory: "1Gi"
              cpu: "1"